modLoader="javafml"
loaderVersion="[33,)"
license="The Unlicense"

[[mods]]
    modId="wthitharvestability"
    version="${file.jarVersion}"
    displayName="WTHIT Harvestability"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/wthit-harvestability"
    issueTrackerURL="https://github.com/badasintended/wthit-harvestability/issues"
    authors="squeek, deirn"
    credits=""
    description='''
    An add-on for WTHIT Forge that adds information about the harvestability of what you are looking at
    '''

[[dependencies.wthitharvestability]]
    modId="wthit"
    mandatory=true
    versionRange="[5.11,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.wthitharvestability]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.wthitharvestability]]
    modId="tconstruct"
    mandatory=false
    versionRange="[3.0.2.73,)"
    ordering="AFTER"
    side="BOTH"
